concept/game/views.py
# -*- coding: utf-8 -*-
"""Game views."""
from flask import Blueprint, render_template, request, redirect, url_for
from random import choice

import base64
import json

from .models import Idea, Concept

blueprint = Blueprint("game", __name__, url_prefix="/game", static_folder="../static")


@blueprint.route("/guess/<conceptcode>")
def guess(conceptcode):
    """Display game."""

    #data = create_game_data()
    data = conceptcode_to_json(conceptcode)
    game_set = get_set()
    return render_template("game/guess.html", data=data, game_set=game_set)

@blueprint.route("/new")
def new():
    """Create a new Idea."""

    concept_set = get_set()
    return render_template("game/create.html", concept_set=concept_set)

@blueprint.route("/random")
def random():
    """Propose a premade concept from a list."""

    return redirect(url_for("game.guess", conceptcode=get_random_concept()))

def get_random_concept():
    concepts = [
        "g0-en-ic26p1c84p1ic16p1c108p1c116p1c105p1-cGl6emE=", # pizza
        "g0-en-ic29p1c3p1ic34p1c17p1ic6p1c58p1c21p1-YmF0bWFu" # batman
    ]
    return choice(concepts)

@blueprint.route("/api/new", methods=['POST'])
def api_create():
    """API to create a new game."""
    conceptcode = json_to_conceptcode(request.get_json())
    return {"conceptcode": conceptcode}

def json_to_conceptcode(json):
    # Set
    gameset = "0"

    # Language
    language = "en"

    jsonideas = json['game']['ideas']
    ideas = ""
    for idea in jsonideas:
        ideacode = ""
        concepts = idea['concepts']
        concepts.sort(key=lambda concept: concept['pos'])
        for concept in concepts:
            ideacode += "c" + str(concept['id']) + "p" + str(concept['points'])
        ideas += "i" + ideacode

    answer = base64.b64encode(json['game']['answer'].encode("utf-8")).decode("utf-8")
    return f"g{gameset}-{language}-{ideas}-{answer}"

def conceptcode_to_json(conceptcode):
    """
    Parse a conceptcode to create a JSON format game data.

    Format is: g0-en-ic4p1c5p3ic4p1c5p3-FGJIZERGOIERJGIOJSDFIG
        * g = start
        * 0 = set
        * en = locale
        * ic4p1c5p3ic4p1c5p3 = ideas/concepts
            * ic4p1c5p2 = idea with main concept as 4 with 1 point and a secondary concept as 5 with 2 points
        * FGJIZERGOIERJGIOJSDFIG = answer
    """
    try:
        sp = conceptcode.split("-")
        gameset = sp[0][1:]
        language = sp[1]

        ideas = []
        is_core = True
        for code_idea in sp[2].split("i")[1:]:
            idea = {"concepts": []} # TODO Missing core
            if is_core:
                idea['is_core'] = True
                is_core = False
            for code_concept in code_idea.split("c")[1:]:
                concept = code_concept.split("p")
                idea['concepts'].append({"id" : concept[0], "points": concept[1]})
            ideas.append(idea)
        answer = base64.b64decode(sp[3].encode("utf-8")).decode("utf-8")
        return json.dumps({"game" : {
            "set": gameset,
            "answer": answer,
            "language": language,
            "ideas": ideas,
        }})
    except:
        print("Something went wrong during the parsing of " + conceptcode)
        return None

def get_set():
    current_set = {
        0 : {'image': 'object.png', 'description': ['Object', 'Thing', 'Package']},
        1 : {'image': 'person.png', 'description': ['Person', 'Family', 'Group']},
        2 : {'image': 'female.png', 'description': ['Female', 'Woman', 'Wife', 'Feminine']},
        3 : {'image': 'male.png', 'description': ['Male', 'Man', 'Husband', 'Masculine']},
        4 : {'image': 'work.png', 'description': ['Work', 'Profession', 'Craft']},
        5 : {'image': 'recreation.png', 'description': ['Recreation', 'Sport', 'Activity']},
        6 : {'image': 'wildlife.png', 'description': ['Wildlife', 'Animal']},
        7 : {'image': 'flora.png', 'description': ['Flora', 'Nature', 'Plant']},
        8 : {'image': 'literature.png', 'description': ['Literature', 'Writing', 'Book']},
        9 : {'image': 'music.png', 'description': ['Music', 'Song', 'Note']},
        10: {'image': 'theater.png', 'description': ['Theater', 'Film', 'Camera']},
        11: {'image': 'arts.png', 'description': ['Arts', 'Scupture', 'Painting', 'Drawing', 'Comics']},
        12: {'image': 'television.png', 'description': ['Television', 'Broadcast', 'Series']},
        13: {'image': 'title.png', 'description': ['Title', 'Brand', 'Name']},
        14: {'image': 'idea.png', 'description': ['Idea', 'Thought', 'Concept']},
        15: {'image': 'expression.png', 'description': ['Expression', 'Quote', 'Speak', 'Word']},
        16: {'image': 'location.png', 'description': ['Location', 'Country', 'Flag']},
        17: {'image': 'building.png', 'description': ['Building', 'Construction', 'City']},
        18: {'image': 'date.png', 'description': ['Date', 'Event', 'Daytime']},
        19: {'image': 'holidays.png', 'description': ['Holidays', 'Birthday', 'Celebration']},
        20: {'image': 'watercraft.png', 'description': ['Watercraft', 'Maritime', 'Swim']},
        21: {'image': 'fly.png', 'description': ['Airborne vehicle', 'Airline', 'Fly']},
        22: {'image': 'car.png', 'description': ['Land vehicle', 'Car', 'Ride']},
        23: {'image': 'tools.png', 'description': ['Tools', 'Construction']},
        24: {'image': 'games.png', 'description': ['Games', 'Toys', 'Youth']},
        25: {'image': 'clothing.png', 'description': ['Clothing', 'Accessories', 'Costume']},
        26: {'image': 'food.png', 'description': ['Food', 'Nutrition', 'Edible']},
        27: {'image': 'home.png', 'description': ['Home', 'Interior', 'Domestic']},
        28: {'image': 'reality.png', 'description': ['Reality', 'History']},
        29: {'image': 'fictional.png', 'description': ['Fictional', 'Imaginary', 'Wish']},
        30: {'image': 'baby.png', 'description': ['Baby', 'Child', 'Young', 'New']},
        31: {'image': 'adult.png', 'description': ['Adult', 'Old', 'Ancient', 'Past']},
        32: {'image': 'slow.png', 'description': ['Slow', 'Lengthy', 'Turtle']},
        33: {'image': 'fast.png', 'description': ['Fast', 'Lively', 'Hare']},
        34: {'image': 'defense.png', 'description': ['Defense', 'Protection', 'Wall']},
        35: {'image': 'conflict.png', 'description': ['Conflict', 'Weapon', 'Fight']},
        36: {'image': 'life.png', 'description': ['Life', 'Heart', 'Love']},
        37: {'image': 'death.png', 'description': ['Death', 'Evil', 'Disease']},
        38: {'image': 'joyous.png', 'description': ['Joyous', 'Positive']},
        39: {'image': 'sad.png', 'description': ['Sad', 'Negative']},
        40: {'image': 'electronics.png', 'description': ['Electronics', 'Computer']},
        41: {'image': 'mechanical.png', 'description': ['Mechanical', 'Industrial']},
        42: {'image': 'money.png', 'description': ['Money', 'Rich', 'Expensive']},
        43: {'image': 'time.png', 'description': ['Time', 'Duration']},
        44: {'image': 'religion.png', 'description': ['Religion', 'Myth', 'Belief']},
        45: {'image': 'power.png', 'description': ['Power', 'Politics']},
        46: {'image': 'science.png', 'description': ['Science', 'Mathematics', 'Chemistry']},
        47: {'image': 'medical.png', 'description': ['Medical', 'Drug', 'Cure']},
        48: {'image': 'head.png', 'description': ['Head', 'Face']},
        49: {'image': 'arm.png', 'description': ['Arm', 'Hand']},
        50: {'image': 'torso.png', 'description': ['Torso', 'Stomach']},
        51: {'image': 'leg.png', 'description': ['Leg', 'Foot']},
        52: {'image': 'ear.png', 'description': ['Ear', 'Sound', 'Hear']},
        53: {'image': 'nose.png', 'description': ['Nose', 'Odor', 'Smell']},
        54: {'image': 'eye.png', 'description': ['Eye', 'View', 'Watch']},
        55: {'image': 'mouth.png', 'description': ['Mouth', 'Flavor', 'Eat']},
        56: {'image': 'cloud.png', 'description': ['Cloud', 'Rain', 'Snow', 'Cold']},
        57: {'image': 'lightning.png', 'description': ['Lightning', 'Electricity', 'Storm', 'Anger']},
        58: {'image': 'night.png', 'description': ['Night', 'Evening', 'Moon']},
        59: {'image': 'sun.png', 'description': ['Sun', 'Heat', 'Light', 'Daytime']},
        60: {'image': 'fire.png', 'description': ['Fire', 'Burn', 'Heat']},
        61: {'image': 'water.png', 'description': ['Water', 'Liquid', 'Aquatic']},
        62: {'image': 'air.png', 'description': ['Air', 'Wind', 'Blow']},
        63: {'image': 'earth.png', 'description': ['Earth', 'Dirt', 'Grow']},
        64: {'image': 'rock.png', 'description': ['Rock', 'Mineral', 'Hard']},
        65: {'image': 'wood.png', 'description': ['Wood']},
        66: {'image': 'metal.png', 'description': ['Metal']},
        67: {'image': 'fabric.png', 'description': ['Fabric']},
        68: {'image': 'plastic.png', 'description': ['Plastic', 'Rubber']},
        69: {'image': 'paper.png', 'description': ['Paper', 'Sheet']},
        70: {'image': 'opposed.png', 'description': ['Opposed', 'Contrary', 'Inverse']},
        71: {'image': 'break.png', 'description': ['Break', 'Separate', 'Half']},
        72: {'image': 'fragment.png', 'description': ['Fragment', 'Multitude', 'Powder']},
        73: {'image': 'part.png', 'description': ['Part', 'Bit', 'Piece']},
        74: {'image': 'inside.png', 'description': ['Inside', 'Internal']},
        75: {'image': 'grid.png', 'description': ['Grid', 'Network', 'Prison']},
        76: {'image': 'zero.png', 'description': ['Zero', 'Nothing', 'Null']},
        77: {'image': 'unity.png', 'description': ['Unity', 'One']},
        78: {'image': 'line.png', 'description': ['Straight line', 'Smooth', 'Rise']},
        79: {'image': 'curve.png', 'description': ['Curve', 'Arc', 'Rounded']},
        80: {'image': 'cross.png', 'description': ['Cross', 'Intersection', 'Addition']},

concept/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    """List members."""
    return render_template("users/members.html")

concept/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

concept/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Mogmi</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:mogmi95@gmail.com">Contact</a></li>
    </ul>
  </small>
</footer>

concept/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/favicon.ico') }}">
    <title>
      {% block page_title %}
      Concept
       {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
    />

    {% block css %}{% endblock %}

    {% if not config['DEBUG'] %}
    <!-- Matomo -->
    <script type="text/javascript">
      var _paq = window._paq = window._paq || [];
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(["setDoNotTrack", true]);
      _paq.push(["disableCookies"]);
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="//matomo.mogmi.fr/";
        _paq.push(['setTrackerUrl', u+'matomo.php']);
        _paq.push(['setSiteId', '1']);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <!-- End Matomo Code -->

    {% endif %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert"
              >&times;</a
            >
            {{ message }}
          </div>
          <!-- end .alert -->
          {% endfor %}
        </div>
        <!-- end col-md -->
      </div>
      <!-- end row -->
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>

concept/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
     Concept
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('game.new') }}">New game
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('game.random') }}">Random game
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.about') }}">About</a>
      </li>
    </ul>
    <!-- {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
    <form class="form-inline" id="loginForm" method="POST" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
        class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">
        <a class="nav-link navbar-text" href="{{ url_for('public.register') }}">Create account</a>
      </li>
    </ul>
    {% endif %}
    -->
  </div><!-- /.navbar-collapse -->
</nav>